# Don't print a new line at the start of the prompt
add_newline = false

[username]
show_always = true

[hostname]
ssh_only = false
disabled = false
prefix = "⟪"
suffix = "⟫"
style = "yellow"

# Replace the "❯" symbol in the prompt with "➜"
[character]     # The name of the module we are configuring is "character"
symbol = "⇒"    # The "symbol" segment is being set to "⇒"

